import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import {SessionProvider} from 'next-auth/react'
import {auth} from '@/auth'
import './globals.css'

const montserrat = Montserrat({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <body className={montserrat.className}>{children}</body>
      </html>
    </SessionProvider>
  )
}
